import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/assets/styles/dashboard.module.scss";

import variables from "@/assets/styles/_variables.module.scss";

import { Layout, Menu, theme, Row, Col, Avatar, Select } from "antd";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
} from "@ant-design/icons";

const inter = Inter({ subsets: ["latin"] });

const { Header, Sider, Content } = Layout;

export default function Home() {
  const [collapsed, setCollapsed] = useState(false);
  const {
    token: { colorBgContainer },
  } = theme.useToken();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>test layout</div>

      <style jsx>{`
        .bg-1 {
          background-color: yellow;
        }
      `}</style>
    </>
  );
}
